// Generated by https://quicktype.io

class Hospitals {
    List<Hospital> hospitals;

    Hospitals({
        this.hospitals,
    });
}

class Hospital {
    String name;
    String location;
    String tel;
    String gps;

    Hospital({
        this.name,
        this.location,
        this.tel,
        this.gps,
    });
}
